### ISSUE TITLE
Cannot destructure property `addComponents` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by bfolkens** [lorisleiva/tailwindcss-plugins#5]
Parcel reports the following after adding `tailwindcss-plugins/pagination` to list.

```
🚨  assets/css/app.css:undefined:undefined: Cannot destructure property `addComponents` of 'undefined' or 'null'.
    at module.exports (assets/node_modules/tailwindcss-plugins/pagination/index.js:41:28)
    at Object.<anonymous> (assets/tailwind.config.js:9:46)
    at Module._compile (assets/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (assets/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at assets/node_modules/tailwindcss/lib/index.js:54:83
    at assets/node_modules/tailwindcss/lib/processTailwindFeatures.js:32:20
```

It looks like the offending line is where the exports is defined:

```
module.exports = function ({ addComponents, theme })
```

Could this be a version mismatch?

(using tailwindcss@1.0.4)

**Comment by bfolkens** [comment]
Work-around:

```
plugins: [
    function({ addUtilities, addComponents, e, prefix, theme, variants, config }) {
    	require('tailwindcss-plugins/pagination')({ addComponents, theme })
    }
]
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for reporting this. I'm not really sure I understand what is causing the issue though. I am not sure how wrapping the plugin in a function and providing it with the exact same variables changes anything.

It could be a Parcel thing (I always use Webpack/Babel for my projects so I'm not really familiar with it).

**Comment by janhenckens** [comment]
Having the same issue with using just postcss & tailwind.

**Comment by bfolkens** [comment]
So as it turns out, doing the following works too (without the trailing `()`):

```
plugins: [
  require('tailwindcss-plugins/pagination')
]
```

**Comment by lorisleiva** [comment]
Ah duh! Sorry, I forgot to update the documentation for the pagination when I upgraded to TailwindCSS 1.x. It has now been updated. Thanks for sharing 👍

**Comment by slava-vishnyakov** [comment]
@lorisleiva I guess this needs updating too:
https://lorisleiva.com/laravel-pagination-with-tailwindcss/

Right now following the instructions I get 'theme is not a function' error.

Thanks!
