### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by lukesnowden** [lorisleiva/tailwindcss-plugins#7]
Hi, I found it difficult to install and configure using the guide in the readme file. Simply posting this if someone else runs into these issues and needs to know how to use;

```javascript
module.exports = {
  theme: {
    pagination: theme => ({
      color: theme('colors.teal.500'),
      link: 'py-2 px-3 bg-white block border-t border-b',
      wrapper: 'justify-start flex my-10',
      item: 'block',
      linkFirst: 'border-l border-r bg-gray-200 rounded-l-sm',
      linkLast: 'border-r border-l bg-gray-200 rounded-r-sm',
    })
  },
  variants: {},
  plugins: [
    require('tailwindcss-plugins/pagination')
  ]
}

```

**Comment by lorisleiva** [comment]
Hi there, thanks for that! 👌 

As mentioned in a more recent [issue](https://github.com/lorisleiva/tailwindcss-plugins/issues/8) I had forgotten to update the documentation for the pagination plugin when I upgraded them to TailwindCSS 1.x. The documentation should now be up-to-date. Thanks again! 🍺
