### ISSUE TITLE
Colors is undefined.

### ISSUE THREAD

**Issue by wishinghand** [lorisleiva/tailwindcss-plugins#8]
After I install with `npm i tailwindcss-plugins -D` and then adding 

```
plugins: [
    require('tailwindcss-plugins/pagination')
]
```

I get an error saying "colors is not defined" whenever I try to add colors either in a configuration object in the plugins, or as a theme.pagination object.
```
theme: {
    pagination: {
      color: colors['green-500'],
    }
}
```

Any idea what I'm doing wrong?

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes, sorry I forgot to update that part of the documentation when I upgraded the plugins to TailwindCSS 1.x.

There is no longer a `colors` variable available on your config file so you must use the function syntax to access your colors.

```js
theme: {
    pagination: theme => ({
      color: theme('colors.green.500'),
    })
}
```

I will update the documentation ASAP.

Thanks for raising this 👍

**Comment by lorisleiva** [comment]
Documentation updated. 🍺
